# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-07 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('messanger', models.CharField(max_length=1000)),
                ('created_event', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
