# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-08 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='messanger',
            new_name='message',
        ),
    ]
