# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-08 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='', upload_to='images/', verbose_name='Image'),
        ),
    ]
