# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-09 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20170309_0317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='message',
            new_name='content',
        ),
    ]
