# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-09 17:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20170309_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
