# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-09 17:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20170310_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
