# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-28 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20170310_0019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
