# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-30 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
